### ISSUE TITLE
REQUEST: css text shadow support

### ISSUE THREAD

**Issue by kokoko3k** [arcan1s/awesome-widgets#112]
Hi and thanks for this tool.
I'm trying to style my text using text-shadow css property, but i'm unable to do it.
this code in a custom script:

```
echo '<div style="text-shadow: 1px 1px #FF0000;">Text-shadow effect</div>'
```

...is rendered without shadow. Is it a qt limitation maybe?

**Comment by arcan1s** [comment]
Hi,

Thank you for the feedback.

Yeah, qml text rendering supports only [limited HTML subset](http://doc.qt.io/qt-5/richtext-html-subset.html) by default, e.g [here is](http://doc.qt.io/qt-5/richtext-html-subset.html#block-attributes) available attributes for `div` tag. I'm afraid the easiest way is only to define `style` for whole widget. Another way is to change default text widget to something else which supports more tags/attributes, but I would avoid this coz it will cause additional load almost without any profit.

**Comment by kokoko3k** [comment]
As i imagined, thanks!

**Comment by kokoko3k** [comment]
Thanks!
I needed to make a new widget for the new settings to work.

**Comment by kokoko3k** [comment]
Thanks!
I needed to make a new widget for the new settings to work.
