### ISSUE TITLE
total == totalkb

### ISSUE THREAD

**Issue by citral** [arcan1s/awesome-widgets#127]
Thanks for making awesome widgets.

When using network data, it seems that the value of <up/down>total == <up/down>totalkb. The expected behavior according to the documentation is that the former should be in megabytes, but it is showing in kilobytes as well.

Example:
`$down $downunits $up $upunits ($downtotal = $downtotalkb $uptotal = $uptotalkb)`

Version: 3.3.2
(If you cannot reproduce, I'll submit more debug info.)

**Comment by arcan1s** [comment]
hi,

yep, can confirm the bug, thank you for reporting
