### ISSUE TITLE
How to show Wi-Fi SSID?

### ISSUE THREAD

**Issue by grossestein** [arcan1s/awesome-widgets#130]
I really wanna know which WiFi I connacted when I neednt click anywhere.could you help me?

**Comment by arcan1s** [comment]
currently there is no out-of-box solution which allows you to show it on widget. 

But you can use custom scripts engine - general solution is to use `iwgetid -r` command to show essid. Other solutions depend on which software do you use to connect to wifi (e.g. like `nmcli -t -f active,ssid dev wifi` or something based on `netctl` parses or even direct `wpa_cli` requests (would not recommend though)).

P.S. I will plan some wifi related features to the next release

**Comment by grossestein** [comment]
Thanks.I think it's not bad to add some other functions,such as the key state,touchpad state , system volume and the brightness of the screen.

**Comment by arcan1s** [comment]
well, i didnt develop this project for a looong time. Meanwhile ssid feature has been added in https://github.com/arcan1s/awesome-widgets/commit/276248a748b1b1f5356cf6e07139d836c3270cf2 and https://github.com/arcan1s/awesome-widgets/commit/e0df575aa993ab10ea5d2c73022ce07c14768381 and scheduled to release 3.4
