### ISSUE TITLE
Formatters have no effects on the $up and $down Tags

### ISSUE THREAD

**Issue by realasking** [arcan1s/awesome-widgets#137]
Hi.
I placed the awesome-widgets on my top panel of plasma 5 desktop. I‘m confused about how to fasten Tags on proper places. The $cpu and $mem tags can be fixed with proper digits settings on the default-float format in the Formatters. However, no formatters could fix the $up and $down Tags. No matter how to set and choose which formatter, their digits are always changed. Is this a bug? And howto solve it ?

**Comment by arcan1s** [comment]
i believe issue is that both `$up` and `$down` converts KB/s to MB/s if related speed is higher than 1MB/s. You probably want to use `$upkb` and `$downkb` with formatters

**Comment by arcan1s** [comment]
closing issue for now, feel free to reopen it if you will have any questions
