### ISSUE TITLE
The widget width keeps on changing

### ISSUE THREAD

**Issue by UtkarshVerma** [arcan1s/awesome-widgets#141]
Is there any way you could format the text so that the width of the widget remains fixed. The issue I'm facing is that the width of the entire widget keeps changing every second as the $cpu value changes, eg. from "2.1" to "3.4".

**Comment by arcan1s** [comment]
you have to use monospace font for that :) most fields have strict length already

**Comment by UtkarshVerma** [comment]
Thanks :)
