### ISSUE TITLE
Values include a not needed `&nbsp;`

### ISSUE THREAD

**Issue by avivace** [arcan1s/awesome-widgets#142]
A lot of values have the non-breaking space HTML entities directly inside the string they resolve to. A lot of times I want the value very near the text before it, especially if I'm putting icons.

![image](https://user-images.githubusercontent.com/14352721/75395258-49b2b580-58f2-11ea-81a7-08879af89d3b.png)

I'm not sure this makes sense, if I want a space I'd put that in the widget configuration.

**Comment by arcan1s** [comment]
:thinking: looks like a bit changed api of notifications (to be precise changed behavior of text placed inside)

**Comment by avivace** [comment]
This is not happening *only* in the notificaiton previewing the values, but also in the actual widget

**Comment by arcan1s** [comment]
should be fixed with 3.4.2

**Comment by avivace** [comment]
Great, thanks
