### ISSUE TITLE
Zscroll feature like in polybar-spotify

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [arcan1s/awesome-widgets#149]
Is it possible to implement scroll functionality like in this project [https://github.com/PrayagS/polybar-spotify](url)?

**Comment by arcan1s** [comment]
hi

Are you talking about buttons or? If you just want spotify support it should already work (just tested with their official client) if you would use `mpris` player settings. If you need the running line you can use an example from documentation

```
${{
function runningLine() {
    var current = "$artist - $title";
    var index = current.indexOf("$this");
    if (("$this" == "") || ((index + 20 + 1) > current.length))
        return current.substring(0, 20);
    else
        return current.substring(index + 1, index + 20 + 1);
}
runningLine()
}}
```

(again just tested it, works normally).

But in case if you would like to have control buttons, it is impossible at the moment (more or less), but there is a feature request https://github.com/arcan1s/awesome-widgets/issues/140

**Comment by 1-minute-to-midnight** [comment]
How do I use this?

**Comment by 1-minute-to-midnight** [comment]
Got it.....I just pasted into the input box and it worked. I thought I had to modify somewhere else. Thanks.
