### ISSUE TITLE
Crashes Latte Dock on Plasma Wayland

### ISSUE THREAD

**Issue by DadangSudadang** [arcan1s/awesome-widgets#151]
Every time I try to add the widget to latte-dock, it crashes the dock (Wayland Plasma). It works fine on X11 Plasma instead however. Any plans for support for Wayland?

I'm not sure what to include here when it crashes. Let me know if you need something.

**Comment by arcan1s** [comment]
yea, i would like to add wayland support, never tested it though since I don't use it :)

* In case if you would run `plasmawindowed org.kde.plasma.awesomewidget` will it crash? 
* if so - could you please attach log from `QT_LOGGING_RULES=*=true plasmawindowed org.kde.plasma.awesomewidget`?
* if not - `QT_LOGGING_RULES=*=true plasmashell` and add widget to cause crash

**Comment by DadangSudadang** [comment]
Thanks for the response! Running `plasmawindowed org.kde.plasma.awesomewidget` shows up fine, but in the terminal it shows this:
```
$ plasmawindowed org.kde.plasma.awesomewidget
kf.plasma.quick: Applet preload policy set to 1
kf.plasma.core: requesting config for "Awesome Widget" without a containment!
[     0.427][WW][org.kde.plasma.awesomewidget][unknown] No keys found
[     0.427][WW][org.kde.plasma.awesomewidget][unknown] No lambdas found
[     0.456][WW][org.kde.plasma.awesomewidget][unknown] No keys found
[     0.457][WW][org.kde.plasma.awesomewidget][unknown] No lambdas found
[     7.677][WW][default][unknown] <Unknown File>:1: TypeError: Cannot read property 'Layout' of null
[     7.704][WW][default][unknown] QObject::disconnect: Unexpected nullptr parameter
```
which doesn't appear in X11. Here's the log with `QT_LOGGING_RULES=*=true`:
[log.txt](https://github.com/arcan1s/awesome-widgets/files/7747139/log.txt)

Putting it on desktop does not cause Plasma to crash however, so it appears that it only affects latte-dock. I tried running `QT_LOGGING_RULES=*=true` on latte-dock and made it crash by switching to a saved layout that has awesome widget in it: 
[log_latte.txt](https://github.com/arcan1s/awesome-widgets/files/7747202/log_latte.txt)

I hope this helps.

**Comment by arcan1s** [comment]
it took more time than i actually expected, but 3.5.0 should introduce full kwayland support

**Comment by DadangSudadang** [comment]
Thank you very much!
