### ISSUE TITLE
there is something wrong with my computer

### ISSUE THREAD

**Issue by ab773628885** [arcan1s/awesome-widgets#154]
[ 57%] Built target org.kde.plasma.awesomewidget-plasmoids-metadata-json
[ 58%] Automatic MOC for target awplugin
[ 58%] Built target awplugin_autogen
[ 59%] Generating ui_awabstractselector.h
[ 60%] Generating ui_awabstractpairconfig.h
[ 61%] Building CXX object awesome-widget/plugin/CMakeFiles/awplugin.dir/awplugin_autogen/mocs_compilation.cpp.o
[ 62%] Building CXX object awesome-widget/plugin/CMakeFiles/awplugin.dir/__/__/awdebug.cpp.o
[ 63%] Building CXX object awesome-widget/plugin/CMakeFiles/awplugin.dir/awabstractpairconfig.cpp.o
[ 63%] Building CXX object awesome-widget/plugin/CMakeFiles/awplugin.dir/awabstractpairhelper.cpp.o
[ 64%] Building CXX object awesome-widget/plugin/CMakeFiles/awplugin.dir/awabstractselector.cpp.o
**[ 65%] Building CXX object awesome-widget/plugin/CMakeFiles/awplugin.dir/awactions.cpp.o
/home/ab77下载/awesome-widgets-development/sources/awesome-widget/plugin/awactions.cpp:28:10: 致命错误：fontdialog/fontdialog.h：没有那个文件或目录   28 | #include <fontdialog/fontdialog.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
编译中断。make[2]: *** [awesome-widget/plugin/CMakeFiles/awplugin.dir/build.make:154: awesome-widget/plugin/CMakeFiles/awplugin.dir/awactions.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:811: awesome-widget/plugin/CMakeFiles/awplugin.dir/all] Error 2
make: *** [Makefile:136: all] Error 2**

**Comment by arcan1s** [comment]
if you are compiling from git sources, you need to checkout submodules also
```
git submodule update --init --recursive
```
It is also noted in installation instruction :)

**Comment by ab773628885** [comment]
sorry , i am new to here .how to use it?

**Comment by arcan1s** [comment]
hmm, how (from where) did you download sources?

**Comment by ab773628885** [comment]
[from this site](https://github.com/arcan1s/awesome-widgets) and click dowload zip 

i cant use kde store to download this :<

and from this site maybe more difficult ：<

**Comment by arcan1s** [comment]
sorry for long reply :(

I've tried to download sources from here https://github.com/arcan1s/awesome-widgets/releases/download/V.3.3.3/awesome-widgets-3.3.3-src.tar.xz (and even 3.3.1 https://github.com/arcan1s/awesome-widgets/releases/download/V.3.3.1/awesome-widgets-3.3.1-src.tar.xz) (kde store just has direct links to it), but still cannot reproduce the issue

Does directory `3rdparty/fontdialog` even contain sources, like
![изображение](https://user-images.githubusercontent.com/2799891/219249199-13f721dd-fb57-4fed-9259-666831d364ae.png)
?

If so could you please provide content of `awesome-widget/plugin/CMakeFiles/awplugin.dir/flags.make` directory (inside `build`)?

**Comment by ab773628885** [comment]
sorry for lont time reply&nbsp;
i mean i download this widget form "kde store", but it can't work.
this is the pic&nbsp; : <

and this is the text for the pic (maybe it can easyer to translate&nbsp; :&gt;)


"/tmp/FlyCgl-awesome-widgets-3.3.3-src.tar.xz 安装失败，因为下载的软件包中不含任何有用的元数据，即该软件包不是有效的 KPackage。"



龙渊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arcan1s/awesome-widgets"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月16日(星期四) 上午10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [arcan1s/awesome-widgets] there is something wrong with my computer (Issue #154)





 
sorry for long reply :(
 
I've tried to download sources from here https://github.com/arcan1s/awesome-widgets/releases/download/V.3.3.3/awesome-widgets-3.3.3-src.tar.xz (and even 3.3.1 https://github.com/arcan1s/awesome-widgets/releases/download/V.3.3.1/awesome-widgets-3.3.1-src.tar.xz) (kde store just has direct links to it), but still cannot reproduce the issue
 
Does directory 3rdparty/fontdialog even contain sources, like
 
 ?
 
If so could you please provide content of awesome-widget/plugin/CMakeFiles/awplugin.dir/flags.make directory (inside build)?

**Comment by arcan1s** [comment]
with 3.5.0 i finally dropped submodules, should not be an issue anymore
