### ISSUE TITLE
Clarify update window

### ISSUE THREAD

**Issue by protist** [arcan1s/awesome-widgets#157]
Firstly, thank you for the great widget. I've been using it for years, and love it!

I launched Plasma today, and I saw three windows each with the title `There are updates — Plasma` and the content
```
3.4.3 (0f28125)
New version : 3.5.1

Click "Ok" to download
```

I had no idea what program was asking me to update! I had to Google the message, which brought me here.

I think the message should have the title of *what program* I'm actually trying to update. In addition, since I install awesome-widgets via the package manager, I don't actually need this update checker running anyway. It would be good to be able to disable it. (Perhaps this could be automatic, e.g. if it's installed in a root-owned directory?)

**Comment by arcan1s** [comment]
:smile: it is possible to disable it already, settings -> advanced, uncheck `Check updates on startup`. The original idea was to notify that there are updates, because it doesn't build itself anyway, probably it should have better wording.

**Comment by protist** [comment]
Oops! Thanks for that info. Sorry I missed it! 🤦

But yes, it would still be great to inform the user which program is creating the window. Thanks again!

**Comment by arcan1s** [comment]
also I think that using standard plasma notification would better fit this feature, I have no idea why did I do it as separated modal window

**Comment by arcan1s** [comment]
fun thing is that modals don't work anymore (it looks like they appear as being child of the panel). So this issue is one of the 4.0.0 blockers
