### ISSUE TITLE
$gpu $gputemp not working after upgrade

### ISSUE THREAD

**Issue by zemerdon** [arcan1s/awesome-widgets#161]
<p align="left">GPU Usage:      $gpu%</p>
<p align="left">GPU Temp:      $gputemp C</p>
</span>

using plasma-widget-awesome-widgets-3.4.3-1.x86_64.deb works fine.

upgraded to plasma-widget-awesome-widgets-3.5.1-1.x86_64.deb and it only shows % and C, no actual sensor data.

**Comment by arcan1s** [comment]
it isn't something i really touched last time :thinking: does it have anything in logs? which gpu/driver are you using?

**Comment by zemerdon** [comment]
glx-alternative-nvidia/oldstable,now 1.2.1~deb11u1 amd64 [installed,automatic]
libegl-nvidia0/oldstable,now 470.199.02-1 amd64 [installed,automatic]
libgl1-nvidia-glvnd-glx/oldstable,now 470.199.02-1 amd64 [installed,automatic]
libgles-nvidia1/oldstable,now 470.199.02-1 amd64 [installed,automatic]
libgles-nvidia2/oldstable,now 470.199.02-1 amd64 [installed,automatic]
libglx-nvidia0/oldstable,now 470.199.02-1 amd64 [installed,automatic]
libnvidia-cbl/oldstable,now 470.199.02-1 amd64 [installed,automatic]
libnvidia-cfg1/oldstable,now 470.199.02-1 amd64 [installed,automatic]
libnvidia-egl-wayland1/oldstable,now 1:1.1.5-1 amd64 [installed,automatic]
libnvidia-eglcore/oldstable,now 470.199.02-1 amd64 [installed,automatic]
libnvidia-encode1/oldstable,now 470.199.02-1 amd64 [installed,automatic]
libnvidia-glcore/oldstable,now 470.199.02-1 amd64 [installed,automatic]
libnvidia-glvkspirv/oldstable,now 470.199.02-1 amd64 [installed,automatic]
libnvidia-ml1/oldstable,now 470.199.02-1 amd64 [installed,automatic]
libnvidia-ptxjitcompiler1/oldstable,now 470.199.02-1 amd64 [installed,automatic]
libnvidia-rtcore/oldstable,now 470.199.02-1 amd64 [installed,automatic]
nvidia-alternative/oldstable,now 470.199.02-1 amd64 [installed,automatic]
nvidia-cuda-mps/oldstable,now 470.199.02-1~deb11u1 amd64 [installed,automatic]
nvidia-driver-bin/oldstable,now 470.199.02-1 amd64 [installed,automatic]
nvidia-driver-libs/oldstable,now 470.199.02-1 amd64 [installed,automatic]
nvidia-driver/oldstable,now 470.199.02-1 amd64 [installed]
nvidia-egl-common/oldstable,now 470.199.02-1 amd64 [installed,automatic]
nvidia-egl-icd/oldstable,now 470.199.02-1 amd64 [installed,automatic]
nvidia-installer-cleanup/oldstable,now 20151021+13 amd64 [installed,automatic]
nvidia-kernel-common/oldstable,now 20151021+13 amd64 [installed,automatic]
nvidia-kernel-dkms/oldstable,now 470.199.02-1 amd64 [installed,automatic]
nvidia-kernel-support/oldstable,now 470.199.02-1 amd64 [installed,automatic]
nvidia-legacy-check/oldstable,now 470.199.02-1 amd64 [installed,automatic]
nvidia-modprobe/bullseye-backports,now 525.78.01-1~bpo11+1 amd64 [installed,automatic]
nvidia-persistenced/oldstable,now 470.103.01-2~deb11u1 amd64 [installed,automatic]
nvidia-settings/oldstable,now 470.141.03-1~deb11u1 amd64 [installed,automatic]
nvidia-smi/oldstable,now 470.199.02-1 amd64 [installed]
nvidia-support/oldstable,now 20151021+13 amd64 [installed,automatic]
nvidia-vdpau-driver/oldstable,now 470.199.02-1 amd64 [installed,automatic]
nvidia-vulkan-common/oldstable,now 470.199.02-1 amd64 [installed,automatic]
nvidia-vulkan-icd/oldstable,now 470.199.02-1 amd64 [installed,automatic]
xserver-xorg-video-nvidia/oldstable,now 470.199.02-1 amd64 [installed,automatic]

**Comment by arcan1s** [comment]
closed as part of #162  migration, gpu sensors are now handled by kde monitor itself
