### ISSUE TITLE
Plasma 6 support

### ISSUE THREAD

**Issue by arcan1s** [arcan1s/awesome-widgets#162]
### General cases

- [x] compile
- [x] packaging
- [x] dependencies update
- [x] configuration
- [x] widget opens
- [x] desktop panel opens
- [x] sysmon sources work
- [x] notifications

### Found issues

- [x] no scroll in settings windows
- [x] desktop source is causing segfault inside kde lib
- [ ] `void *` cast to widget for translation
- [x] no time source
- [x] AMD load/temperature definitely don't work, nvidia probably too (see #161)
- [x] there is no unsubscribe events for root sources (e.g. `extsysmon`)
- [x] #164
- [x] #165
- [x] no history
- [x] no button colors

### Tags

- [x] $time
- [x] $isotime
- [x] $shorttime
- [x] $longtime
- [x] $ctime
- [x] $tstime
- [x] $uptime
- [x] $cuptime
- [x] $la1
- [x] $la5
- [x] $la15
- [x] $cpu
- [x] $cpuN
- [x] $cpucl
- [x] $cpuclN
- [x] $tempN
- [x] $gpu (plus `$gpuN`)
- [x] $gputemp (superseded by `$gputempN`)
- [x] $mem
- [x] $memmb
- [x] $memgb
- [x] $memfreemb
- [x] $memfreegb
- [x] $memtotmb
- [x] $memtotgb
- [x] $memusedmb
- [x] $memusedgb
- [x] $swap
- [x] $swapmb
- [x] $swapgb
- [x] $swapfreemb
- [x] $swapfreegb
- [x] $swaptotmb
- [x] $swaptotgb
- [x] $hddN
- [x] $hddmbN
- [x] $hddgbN
- [x] $hddfreembN
- [x] $hddfreegbN
- [x] $hddtotmbN
- [x] $hddtotgbN
- [x] $hddrN
- [x] $hddwN
- [x] ~$hddtempN~ **DEPRECATED USE temp instead**
- [x] $down
- [x] $downkb
- [x] $downunits
- [x] $downtot
- [x] $downtotkb
- [x] $downN
- [x] $downkbN
- [x] $downunitsN
- [x] $downtotN
- [x] $downtotkbN
- [x] $up
- [x] $upkb
- [x] $upunits
- [x] $uptot
- [x] $uptotkb
- [x] $upN
- [x] $upkbN
- [x] $upunitsN
- [x] $uptotN
- [x] $uptotkbN
- [x] $netdev
- [x] $bat
- [x] $batN
- [x] $ac
- [x] $album
- [x] $dalbum
- [x] $salbum
- [x] $artist
- [x] $dartist
- [x] $sartist
- [x] $duration
- [x] $progress
- [x] $title
- [x] $dtitle
- [x] $stitle
- [x] $ps
- [x] $pscount
- [x] $pstot
- [x] $pkgcountN
- [x] $responseN
- [x] $customN
- [x] $desktop
- [x] $ndesktop
- [x] $tdesktops
- [x] $percpricechgN
- [x] $percvolumechgN
- [x] $priceN
- [x] $pricechgN
- [x] $volumeN
- [x] $volumechgN
- [x] $weatherIdN
- [x] $weatherN
- [x] $humidityN
- [x] $pressureN
- [x] $temperatureN
- [x] brightness
- [x] volume
- [x] ssid

### Desktop panel tags

- [x] $mark
- [x] $name
- [x] $number
- [x] $total

**Comment by protist** [comment]
Thanks again for this widget. It is an essential part of my system. I have several instances for different purposes, but the most important one is as an email notifier.

I know that you only just opened this issue recently, but Plasma 6 has now dropped in the stable Arch Linux repos. I was just wondering if you were working on Plasma 6 support now and/or if you have a sense of when this might be completed.

I have absolutely no expectation of this FOSS project, and I certainly don't mean to be pushy, but I just wanted a get a sense of whether I should freeze all my system updates and wait, or whether I should just update and find a workaround in the meantime. Thank you.

**Comment by arcan1s** [comment]
hey! Well, yeah, I just updated my systems recently and started working on porting. Unfortunately kde has totally dropped old infrastructure with dataengines together with ksysguard (somewhat related to https://github.com/arcan1s/awesome-widgets/pull/159), I'm trying to figure out how to fix it asap (preferably without loosing features), but no eta yet unfortunately :( development branch is https://github.com/arcan1s/awesome-widgets/tree/feature/plasma6

**Comment by protist** [comment]
Thanks @arcan1s . I appreciate how fiddly it must be. Thank you for your continued development of this widget!

**Comment by arcan1s** [comment]
aight, I got working instance of widget, no settings, no extensions, some functions are totally unavailable. From the current perspective I'd say it will be possible to tag alpha version (extensions and most of functionality, more likely bugged) in two weeks and after that start on remaining features

**Comment by protist** [comment]
Thank you @arcan1s! That's great to hear! I look forward to the update. I only ever use Awesome widgets to display the output of CLI scripts anyway, so I don't use most of the other functions. I'd love to see an early version too if possible, even if highly buggy. Thanks again!

**Comment by arcan1s** [comment]
the first part of porting is done, I've been able to install it to the system and run (on somewhat near default configuration) it. I've updated OP and added checklist, so anyone would be able to see what is supposed to work at the moment

**Comment by arcan1s** [comment]
first alpha has been released and available in aur https://aur.archlinux.org/packages/plasma6-applet-awesome-widgets. Most features have been restored, as well as some new (e.g. better handling of gpu devices) have been added

Now I'm going to review changes again and do some rework

**Comment by protist** [comment]
That's fantastic. Thank you @arcan1s for the super quick work on this! Very much appreciated.
