### ISSUE TITLE
Temperature doesn't support tempN properly

### ISSUE THREAD

**Issue by divansantana** [arcan1s/awesome-widgets#17]
Hi,

Firstly this is awesome so thank you.

Secondly, I think the temperature component is not working correctly.
By default it's set to:
`[temp: $temp0&deg;C]`

However on my system I need it set to temp1 as temp0 doesn't exist:

```
# /usr/bin/sensors -u    
asus-isa-0000
Adapter: ISA adapter
temp1:
  temp1_input: 48.000

coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:
  temp1_input: 50.000
  temp1_max: 100.000
  temp1_crit: 100.000
  temp1_crit_alarm: 0.000
Core 0:
  temp2_input: 50.000
  temp2_max: 100.000
  temp2_crit: 100.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 48.000
  temp3_max: 100.000
  temp3_crit: 100.000
  temp3_crit_alarm: 0.000
```

When I set it to 

```
[temp: $temp1&deg;C]
```

It literally displays

```
[temp: $temp1&deg;C]
```

Instead of converting `$temp1` to a variable as expected.

**Comment by danieledipompeo** [comment]
Hi,
First, I have finally found the best status bar :) thanks.

I cannot show the ```$temp0``` value. I'm using the awesome widget on KUbuntu 20.04, and the GUI is quite different from the example above. 

Can you help me to configure the status bar?

here below my ```sensors -u```
```amdgpu-pci-0100
Adapter: PCI adapter
vddgfx:
  in0_input: 0.725
fan1:
  fan1_input: 814.000
  fan1_min: 0.000
  fan1_max: 3200.000
edge:
  temp1_input: 35.000
  temp1_crit: 94.000
  temp1_crit_hyst: -273.150
power1:
  power1_average: 31.160
  power1_cap: 155.000

acpitz-acpi-0
Adapter: ACPI interface
temp1:
  temp1_input: 6.800
  temp1_crit: 18.800
temp2:
  temp2_input: 27.800
  temp2_crit: 119.000
temp3:
  temp3_input: 29.800
  temp3_crit: 119.000

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:
  temp1_input: 37.000
  temp1_max: 82.000
  temp1_crit: 100.000
  temp1_crit_alarm: 0.000
Core 0:
  temp2_input: 35.000
  temp2_max: 82.000
  temp2_crit: 100.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 37.000
  temp3_max: 82.000
  temp3_crit: 100.000
  temp3_crit_alarm: 0.000
Core 2:
  temp4_input: 35.000
  temp4_max: 82.000
  temp4_crit: 100.000
  temp4_crit_alarm: 0.000
Core 3:
  temp5_input: 36.000
  temp5_max: 82.000
  temp5_crit: 100.000
  temp5_crit_alarm: 0.000
Core 4:
  temp6_input: 36.000
  temp6_max: 82.000
  temp6_crit: 100.000
  temp6_crit_alarm: 0.000
Core 5:
  temp7_input: 35.000
  temp7_max: 82.000
  temp7_crit: 100.000
  temp7_crit_alarm: 0.000
```
Here below the advanced tab, where I cannot find what you have suggested.

![image](https://user-images.githubusercontent.com/2399323/103806326-22219300-5055-11eb-81a5-1769e54da037.png)

**Comment by arcan1s** [comment]
temperature tags are now generating automatically from system dataengine. Do you have `plasmaengineexplorer` installed (it should be in `plasma-sdk` package or something like that)? It should have something like

![изображение](https://user-images.githubusercontent.com/2799891/103847928-4cee0480-50b2-11eb-8918-c70e4062e972.png)

also you can check parsed lmsensors devices from cache file (`~/.cache/awesomewidgets.ndx`, section called `temp`) or alternatively from widget settings you can ask for popup:

![изображение](https://user-images.githubusercontent.com/2799891/103848163-d271b480-50b2-11eb-9799-998a86a420fd.png)

**Comment by danieledipompeo** [comment]
Thx...
I haven't yet installed ```plasmaengineexplorer```.
Reading the ```~/.cache/awesomewidgets.ndx``` I can get data about cpu, mem, and hdd (mounted partitions). However, I still have a problem with the GPU usage and temp.
Here below the output of ```sensors```
![image](https://user-images.githubusercontent.com/2399323/104089894-db10e900-5272-11eb-9240-5c9a8efea0ef.png)

and here the output of ```~/.cache/awesomewidgets.ndx```
![image](https://user-images.githubusercontent.com/2399323/104089909-fe3b9880-5272-11eb-9ca9-935abf3166f2.png)

As far as I understood, I have updated the widget in this way
```[cpu: $cpu% $temp6&deg;C] [gpu: $gpu% $gputemp2&deg;C] [mem: $memgbGB ($mem%)] [swap: $swap%] [/: $hddgb1GB ($hdd1%)] [/opt: $hddgb3GB ($hdd3%)] [$netdev: $down/$upKB/s] [uptime: $cuptime]```

and the output is below
![image](https://user-images.githubusercontent.com/2399323/104089925-2c20dd00-5273-11eb-8454-41a2554aa8d2.png)

Can you understand where I use wrong setting?

Meanwhile, I play with different configurations.

BR
D.

**Comment by danieledipompeo** [comment]
Thx...
I haven't yet installed ```plasmaengineexplorer```.
Reading the ```~/.cache/awesomewidgets.ndx``` I can get data about cpu, mem, and hdd (mounted partitions). However, I still have problem with the GPU usage and temp.
Here below the output of ```sensors```
![image](https://user-images.githubusercontent.com/2399323/104090003-cd0f9800-5273-11eb-85ae-0244109c1224.png)

and here the output of ```~/.cache/awesomewidgets.ndx```
![image](https://user-images.githubusercontent.com/2399323/104089909-fe3b9880-5272-11eb-9ca9-935abf3166f2.png)

As far as I understood, I have updated the widget in this way
```[cpu: $cpu% $temp6&deg;C] [gpu: $gpu% $gputemp2&deg;C] [mem: $memgbGB ($mem%)] [swap: $swap%] [/: $hddgb1GB ($hdd1%)] [/opt: $hddgb3GB ($hdd3%)] [$netdev: $down/$upKB/s] [uptime: $cuptime]```

and the output is below
![image](https://user-images.githubusercontent.com/2399323/104089925-2c20dd00-5273-11eb-8454-41a2554aa8d2.png)

Can you understand where I use wrong setting?

Meanwhile, I play with different configurations.

BR
D.

**Comment by arcan1s** [comment]
temperature seems to be alright, but for gpu there are several limitations

* it only has `$gpu` and `$gputemp` tags and supposes that there is only 1 gpu for which you can measure things
* it only supports amd and nvidia
* it requires to have `aticonfig` and `nvidia-smi` executables respectively
* I'm not even sure if it works with amdgpu, this part has been written for old `fglrx` driver (at least `GPUDEV=auto` will not recognize ati in this case). Also sadly I don't have access to device with amdgpu, so I can't even adapt the code (thou it should be easy probably)

At least I can say that in your case you can use `$temp2` as "gpu temperature" because it is in sensors output and has been already parsed by kde dataengine
