### ISSUE TITLE
Manually specify width in panels

### ISSUE THREAD

**Issue by protist** [arcan1s/awesome-widgets#47]
In Plasma 5, when I add awesome-widgets to a panel, there is quite a lot of padding.
![Screenshot](https://i.imgur.com/o4qHZIQ.png)

Also, the width is not fixed, so (for example) when the taskbar fills up, the padding of awesome-widgets decreases. Ideally, there should be an option for users to specify a fixed width of the plasmoid in pixels. This might also require additional options, such as whether text should be centred, or left/right aligned.

Another additional option might be for users to specify a fixed amount of padding either side of the text.

**Comment by arcan1s** [comment]
yep, I'm on this problem at the moment. It will be fixed in the next release. Thank you for the reporting.

**Comment by protist** [comment]
Thanks for the quick response and fix.
