### ISSUE TITLE
Increase maximum refresh time

### ISSUE THREAD

**Issue by protist** [arcan1s/awesome-widgets#48]
The maximum refresh time seems to be limited to 10 seconds. Would it be possible to remove this limitation? For example, the included custom command to show your external IP would only need to be refreshed every hour or so.

**Comment by arcan1s** [comment]
It is limited only by UI and may be removed easily. But custom scripts has own implementation of intervals (`X-AW-Interval` key). This interval is a times in standard intervals when a script will be run. But seems script UI has own limit for this value, in your case  you may edit scripts (path are `/usr/share/awesomewidgets/scripts/` and `~/.local/share/awesomewidgets/scripts/`) and place required parameter for the `X-AW-Interval` key.

Also I'll reconsider the limits in the UI to the next release

**Comment by protist** [comment]
Thank you for the clarification. Cheers.
