### ISSUE TITLE
Allow multiple lines of output

### ISSUE THREAD

**Issue by protist** [arcan1s/awesome-widgets#53]
I'd love to have my `todo.sh` list on the dashboard, but Awesome Widgets doesn't appear to process newlines correctly. It'd be great if we could have multi-line output.

(Also, interpreting ANSI colour codes would be very cool; I'm happy to open up a new issue for this if you like.)

**Comment by arcan1s** [comment]
As far as I remember my tests, only `<br>` is recognizable as new line separator.

The general idea is to support on text configuration HTML only. In this context I may suggest you two cases which may be implemented on my side:

1. For configuration create "Replace `\n` to `<br>`" checkbox.
2. For custom commands create a special filters which should be selected from interface. For your example they are may be:
    1. Replace `\n` to `<br>`
    2. Convert shell colours to html

**Comment by arcan1s** [comment]
jfyi i've implemented both of them but didn't test yet

**Comment by arcan1s** [comment]
hmm, I've improved the filters so except for standard filters (color, `\n` and `\t`, spaces) it may apply any other custom filter

**Comment by arcan1s** [comment]
will be released on this week if all will be ok

**Comment by protist** [comment]
Apologies for the delay in response. In terms of where to place settings, I'm a little conflicted. It'd be useful to select interpretation of '\n' and colour for the widget as a whole, so that users could insert newlines between their non-custom commands. However, making the option specific to individual custom commands gives more control to users. I guess I tend towards the former, but very slightly.

In terms of filters, I think you have them all covered. I had a quick [read](http://www.tldp.org/LDP/abs/html/escapingsection.html) but the only other possibility might be `\r`. Obviously it's fairly rare, and probably not even worth considering for *nix users. Thanks for the quick response.

**Comment by arcan1s** [comment]
ok thanks for the feedback, will implement `\r` to the filter list

**Comment by arcan1s** [comment]
implemented. As far as there is no any plan for the future release, the new version will be released on Monday.

**Comment by protist** [comment]
I just tested and it's working great! However, I'm finding a really strange bug; it's not printing v's! For example, the following desktop file.

    [Desktop%20Entry]
    Comment=Print todo list
    Encoding=UTF-8
    Exec=\"echo A caravan of travellers.\"
    Name=todo.desktop
    X-AW-Active=true
    X-AW-ApiVersion=3
    X-AW-Filters="color,newline"
    X-AW-Interval=60
    X-AW-Number=3
    X-AW-Output=true
    X-AW-Prefix=bash -c
    X-AW-Redirect=nothing

**Comment by arcan1s** [comment]
hm, please remove line `25` at `/usr/share/awesomewidgets/scripts/awesomewidgets-extscripts-filters.json` and comma at the end of line `24`

**Comment by protist** [comment]
Perfect! I can confirm that v's now work perfectly.

**Comment by protist** [comment]
Also, related to multiple lines, having left justification as an option instead of centred would be excellent. I'm happy to open up a new issue if you like.

**Comment by arcan1s** [comment]
it should be supported by html tags. Smth like `<p align="right">$custom</p>`

**Comment by protist** [comment]
Oh brilliant! Thanks for that!
