### ISSUE TITLE
Multiple instances no longer work

### ISSUE THREAD

**Issue by protist** [arcan1s/awesome-widgets#57]
I upgraded my system this morning, and multiple instances of awesome-widgets no longer work. I have three instances of awesome widgets, all displaying different custom commands (let's call the commands `a`, `b` and `c`). However, all three instances show the same identical output (`a`). I can right click on each instance, select `Awesome Widget Settings…`, and confirm that they are configured to show different outputs.

In addition, if I check the settings for the instance defined as `b`, I then click `Cancel`, and all instances then show `b`'s output! I can repeat this for `c` and `a` to make all three instances show the expected output for both of these instances.

There were a few KDE upgrades this morning; seemingly, all relate to the upgrade of KDE Frameworks from 5.11.0 to 5.12.0. I'm happy to troubleshoot more if necessary.

Arch Linux
Plasma 5.3.2
Awesome widgets 2.3.3 (from AUR)

**Comment by arcan1s** [comment]
thanks, I may confirm it. But in other hand I don't change any configuration related logic for a long time, so seems this behaviour is associated with plasma upgrade.

I'll look at this bug and create workaround as soon as possible.

**Comment by arcan1s** [comment]
hello again,

I've prepared a hotfix which allows to run several instances 4e78e0e1dd7104c957a4dac2dcd5142b6982b263. But unfortunately it may cause some additional CPU load. Nevertheless I think you may build plasmoid from git and use it as a temporary solution.

**Comment by protist** [comment]
Thanks for the quick fix. This definitely fixes the problem. However, I'm not sure how to tell how much CPU it's using. `plasmashell` is now using 27–30% of one core at idle, but I'm not sure how to tell if it's awesome widget specifically.

**Comment by protist** [comment]
Okay, this is interesting. The CPU load is tolerable, but xorg was using about 5 GB of RAM. I restarted, and xorg was up to 4 GB in 30–60 minutes. I then downgraded awesome widget back to 2.3.3, and restarted. Now after 45 minutes, xorg is only using 100 MB. (Also, FWIW, `plasmashell` is now only using 10–15% of a core.)

**Comment by arcan1s** [comment]
Unfortunately could not confirm so large usage. As for me plasma uses from 200M to 400M and seems there is no a tendency to this value being increased.

Could you please provide me details which commands you are using and which intervals are?

**Comment by protist** [comment]
N.B. that it's not `plasmashell` that has the large memory usage, it's `xorg` (i.e. in `htop`, listed as `/usr/lib/xorg-server/Xorg :0 -auth /var/run/sddm/:0 -nolisten tcp -background none -noreset vt1`). Also, from inspecting `htop` for ~30 seconds previously, memory usage appeared to be increasing fairly regularly. As you can see below, the quickest widget instance is only updating every minute, so I *suspect* that's it's unrelated to the widget command itself, although I'm not sure.

I'm using three widgets.

1. On the "desktop", running `/usr/bin/todo.sh` from [AUR](https://aur.archlinux.org/packages/todotxt/), updating every 60 seconds.
2. In a panel, running `/usr/local/bin/temperature_current` (see below) updating every 10 minutes.
3. In a panel, running `/usr/local/bin/temperature_forecast` (see below) updating every 10 minutes.

`/usr/local/bin/temperature_current`:
```
#!/usr/bin/env bash
echo `curl --silent "http://www.bom.gov.au/vic/observations/melbourne.shtml"|grep -Po "<td headers=\"obs-temp obs-station-essendon-airport\">\K.*(?=</td>)"`°C
```

`/usr/local/bin/temperature_forecast`:
```
#!/usr/bin/env bash
curl --silent http://www.bom.gov.au/vic/forecasts/melbourne.shtml 2>/dev/null | grep -m2 '<h2>' -A8 | tail -9 | grep -oP '((?<=<h2>)...|(?<=<dd>Min <em class=\"min\">)..|(?<=<dd>Max <em class=\"max\">)..)' | tr -d '\n' | sed -r 's/^(...)(.[^<]?)<?(.[^<]?)<?$/\2–\3°C(\1)/'
```

**Comment by arcan1s** [comment]
thanks. Seems really there is a some issue here (as I said earlier I could not reproduce it precisely, but I may confirm that there is a same issue on one of my pc). I'll look on it, hope the next release will have some fixes on this side (but unfortunately, I could not provide any ETA atm).

**Comment by arcan1s** [comment]
btw, I think that increasing update time (and decreasing intervals for scripts) should partially solve your issue.

**Comment by protist** [comment]
Thanks for that. Just to confirm, are you saying that making updates *more* frequent will reduce memory usage? It's just a bit unintuitive, and I presume that this might increase CPU more?

**Comment by arcan1s** [comment]
I suppose you **increase** the main update time (settings are in Appearance tab) and **decrease** the custom scripts intervals (to leave them with the same *time intervals* as they are).

The current widget architecture leads to the fact that the widget subscribes on all available data from plasma. Since you don't use these data, I believe you may set intervals more than default is (1000 msec).

**Comment by arcan1s** [comment]
please leave this note without attention it is an internal one.

Probably the issue may be caused by the moving plugin from private to public group (ref to c6cadba4b649626b81d7cf78ae7d50390ee8bb15). Trying to revert the changes, seeing what will be broken. Nevertheless this revert still require changes from 4e78e0e1dd7104c957a4dac2dcd5142b6982b263. 

Another possible way to improve performance (at least to decrease cpu load) is to use signal slot model for the text update (i.e. emit signal from plugin with the text as an argument), but it will increase amount of JS-C++ calls and may degrade the performance.

Also perhaps change architecture to "lazzy" updates will solve some issues. But it is epic task and may require to rewrite a part of plugin.

**Comment by arcan1s** [comment]
ok I've turned back key filtering. Now it should be the same as it was. Also I've planned the update widget to lazy updates with 2.4.0 release (still no ETA).

**Comment by protist** [comment]
Thank you. I installed the git version from your PKGBUILD, but unfortunately this still doesn't handle multiple instances correctly. The widget showing command `a` works fine, but the other two are showing a literal `$custom2` and `$custom3`.

As above, I can check the settings for the instance defined as `b`, then click Cancel. This instance then displays `b`'s output as expected, but the instance for `a` now shows a literal `$custom1`. I can repeat this at will; only one instance's output is shown at a time correctly.

**Comment by arcan1s** [comment]
urgh, sorry. In order to do not create a new kludges, I've asked in the plasma-devel@ mailing list. I'll wait for their answer and apply fixes then. Sorry for your trouble.

**Comment by protist** [comment]
No, no! It's no problem at all! This plasmoid is so useful. It's really the most versatile one around by far. I'm more than happy to troubleshoot with you. I'll wait for the fix in the meantime, and thank you for your attention to these bugs! Cheers.

**Comment by arcan1s** [comment]
thank you for your feedback, such comments  promote an improvement of own programs :)

Nevertheless, I've got a reply on my question and applied the correct fix. Not sure that it will no cause the large memory usage again, but it should more correct solution of the issue. I'll push commit soon to you may try it too.

**Comment by protist** [comment]
No problem! Thanks again for the quick fix; it seems to be working perfectly now. About an hour later and Xorg is at "normal" RAM usage. Thank you very much!
