### ISSUE TITLE
Не удаляются свои элементы dataengine.

### ISSUE THREAD

**Issue by KottV** [arcan1s/awesome-widgets#60]
Приветствую. Если создать свой скрипт/погоду/котировку/, то удалить его потом кнопочкой не получатеся.
Если нужен дебаг - приложу.

**Comment by arcan1s** [comment]
привет,

Да, посмотрю.

**Comment by arcan1s** [comment]
Это кстати, хайзенбаг в чистом виде. Из за моих кривых рук, оно удаляет итемы тогда и только тогда, когда включен дебаг =)
