### ISSUE TITLE
[Regression] awesome-widgets 3.1.0 fails to build

### ISSUE THREAD

**Issue by protist** [arcan1s/awesome-widgets#87]
I tried upgrading to the latest version 3.1.0, but it fails to build. I followed the [instructions](https://github.com/arcan1s/awesome-widgets#installation) on the Readme, but it fails at the `make` step. Error logs [here](https://gist.github.com/protist/12c539e7a888f9bf51d98bc5a26827f6). I'm using Plasma 5, but it fails whether I use `-DKDE_INSTALL_USE_QT_SYS_PATHS=ON` in the previous step or not.

**Comment by revoluzzer** [comment]
i have the same problem with the aur/PKGBUILD-git and the source.

**Comment by protist** [comment]
Yes, FWIW this originally failed for me with the (non-git) AUR plasma5-applet-awesome-widgets 3.0.1-1, but I could replicate the failure directly from upstream.

**Comment by arcan1s** [comment]
sorry :( didnt rebuild it in clear chroot for some time, just found the same error while trying to build ubuntu packages

**Comment by arcan1s** [comment]
hmm, actually the error occurs only while using gcc, clang produces no errors :/

**Comment by protist** [comment]
Thanks for the quick fix! I just realised you were the AUR maintainer too, so sorry for spamming you! :)

**Comment by protist** [comment]
Also, I can confirm that it builds fine for me now (from the AUR package). Thanks again!
