### ISSUE TITLE
[REGRESSION] Vertical alignment in panels is offset

### ISSUE THREAD

**Issue by protist** [arcan1s/awesome-widgets#94]
I just upgraded from 3.1.1 to 3.1.2 (from the Arch Linux AUR packages). I have some widgets in a panel, but the vertical alignment has changed from the previous version. Previously, the text would be centred vertically. Now it's offset, as below.

![Offset vertical alignment](https://cloud.githubusercontent.com/assets/646668/15101194/ef79c994-15cc-11e6-807d-91551d150b7a.png)

I had a look at various options, but couldn't see a way to change it.

**Comment by arcan1s** [comment]
Yep, actually it is some kind of known issue which has been introduced by https://github.com/arcan1s/awesome-widgets/commit/aef1a736c8b5a10d2b81ad0682f6233a055502e5#diff-6627d370a77373e5b1e33998c356cfd5L87 about which I have totally forgotten.

As a temporary solution I suggest you to edit `/usr/share/plasma/plasmoids/org.kde.plasma.awesomewidget/contents/ui/main.qml` and revert this changes.

The reason to introduce this changes is the fact that plasmoid area in the old case is too more than text has:

old code:
![1](https://cloud.githubusercontent.com/assets/2799891/15101513/544539a0-15a3-11e6-9b70-9a642a7496f8.png)

new code:
![aw-release](https://cloud.githubusercontent.com/assets/2799891/15100499/833c0d8e-1584-11e6-9422-0d8cbe856341.png)

**Comment by arcan1s** [comment]
should be fixed with AUR package 3.1.2-2

**Comment by protist** [comment]
Perfect! Thanks for the ridiculously fast fix! :+1:
